test-lambda-three-handler:
  handler: lambda_handler.lambda_handler #handler function
  name: test-lambda-three  #lambda function name
  module: test-lambda-three
  memorySize: 128
#  environment:
#    CONFIG: >-
#      ${ssm:test_lambda_one_env_variable}
  package:
    patterns:
      - '!./**'
      - './test-lambda-three/**'